// Generated by gencpp from file test/display_draw_rectangle.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_DISPLAY_DRAW_RECTANGLE_H
#define TEST_MESSAGE_DISPLAY_DRAW_RECTANGLE_H

#include <ros/service_traits.h>


#include <test/display_draw_rectangleRequest.h>
#include <test/display_draw_rectangleResponse.h>


namespace test
{

struct display_draw_rectangle
{

typedef display_draw_rectangleRequest Request;
typedef display_draw_rectangleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_draw_rectangle
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::display_draw_rectangle > {
  static const char* value()
  {
    return "f7d77dd6f16a5d7e8ba643de53791446";
  }

  static const char* value(const ::test::display_draw_rectangle&) { return value(); }
};

template<>
struct DataType< ::test::display_draw_rectangle > {
  static const char* value()
  {
    return "test/display_draw_rectangle";
  }

  static const char* value(const ::test::display_draw_rectangle&) { return value(); }
};


// service_traits::MD5Sum< ::test::display_draw_rectangleRequest> should match 
// service_traits::MD5Sum< ::test::display_draw_rectangle > 
template<>
struct MD5Sum< ::test::display_draw_rectangleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::display_draw_rectangle >::value();
  }
  static const char* value(const ::test::display_draw_rectangleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::display_draw_rectangleRequest> should match 
// service_traits::DataType< ::test::display_draw_rectangle > 
template<>
struct DataType< ::test::display_draw_rectangleRequest>
{
  static const char* value()
  {
    return DataType< ::test::display_draw_rectangle >::value();
  }
  static const char* value(const ::test::display_draw_rectangleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::display_draw_rectangleResponse> should match 
// service_traits::MD5Sum< ::test::display_draw_rectangle > 
template<>
struct MD5Sum< ::test::display_draw_rectangleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::display_draw_rectangle >::value();
  }
  static const char* value(const ::test::display_draw_rectangleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::display_draw_rectangleResponse> should match 
// service_traits::DataType< ::test::display_draw_rectangle > 
template<>
struct DataType< ::test::display_draw_rectangleResponse>
{
  static const char* value()
  {
    return DataType< ::test::display_draw_rectangle >::value();
  }
  static const char* value(const ::test::display_draw_rectangleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_DISPLAY_DRAW_RECTANGLE_H
