// Generated by gencpp from file test/display_image_copyResponse.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_DISPLAY_IMAGE_COPYRESPONSE_H
#define TEST_MESSAGE_DISPLAY_IMAGE_COPYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct display_image_copyResponse_
{
  typedef display_image_copyResponse_<ContainerAllocator> Type;

  display_image_copyResponse_()
    : ir(0)  {
    }
  display_image_copyResponse_(const ContainerAllocator& _alloc)
    : ir(0)  {
  (void)_alloc;
    }



   typedef uint64_t _ir_type;
  _ir_type ir;





  typedef boost::shared_ptr< ::test::display_image_copyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::display_image_copyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct display_image_copyResponse_

typedef ::test::display_image_copyResponse_<std::allocator<void> > display_image_copyResponse;

typedef boost::shared_ptr< ::test::display_image_copyResponse > display_image_copyResponsePtr;
typedef boost::shared_ptr< ::test::display_image_copyResponse const> display_image_copyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::display_image_copyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::display_image_copyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test': ['/home/nbhak/Desktop/test_ws/src/test/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test::display_image_copyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::display_image_copyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::display_image_copyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::display_image_copyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::display_image_copyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::display_image_copyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::display_image_copyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "062bd6ec8c99fd70e30cc24256f9226a";
  }

  static const char* value(const ::test::display_image_copyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x062bd6ec8c99fd70ULL;
  static const uint64_t static_value2 = 0xe30cc24256f9226aULL;
};

template<class ContainerAllocator>
struct DataType< ::test::display_image_copyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/display_image_copyResponse";
  }

  static const char* value(const ::test::display_image_copyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::display_image_copyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 ir\n\
\n\
";
  }

  static const char* value(const ::test::display_image_copyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::display_image_copyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct display_image_copyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::display_image_copyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::display_image_copyResponse_<ContainerAllocator>& v)
  {
    s << indent << "ir: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.ir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_DISPLAY_IMAGE_COPYRESPONSE_H
