// Generated by gencpp from file test/lidar_get_frequency_infoResponse.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_LIDAR_GET_FREQUENCY_INFORESPONSE_H
#define TEST_MESSAGE_LIDAR_GET_FREQUENCY_INFORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct lidar_get_frequency_infoResponse_
{
  typedef lidar_get_frequency_infoResponse_<ContainerAllocator> Type;

  lidar_get_frequency_infoResponse_()
    : frequency(0.0)
    , minFrequency(0.0)
    , maxFrequency(0.0)  {
    }
  lidar_get_frequency_infoResponse_(const ContainerAllocator& _alloc)
    : frequency(0.0)
    , minFrequency(0.0)
    , maxFrequency(0.0)  {
  (void)_alloc;
    }



   typedef double _frequency_type;
  _frequency_type frequency;

   typedef double _minFrequency_type;
  _minFrequency_type minFrequency;

   typedef double _maxFrequency_type;
  _maxFrequency_type maxFrequency;





  typedef boost::shared_ptr< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct lidar_get_frequency_infoResponse_

typedef ::test::lidar_get_frequency_infoResponse_<std::allocator<void> > lidar_get_frequency_infoResponse;

typedef boost::shared_ptr< ::test::lidar_get_frequency_infoResponse > lidar_get_frequency_infoResponsePtr;
typedef boost::shared_ptr< ::test::lidar_get_frequency_infoResponse const> lidar_get_frequency_infoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test': ['/home/nbhak/Desktop/test_ws/src/test/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9814880637e7548b4e9c8076e7471dc3";
  }

  static const char* value(const ::test::lidar_get_frequency_infoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9814880637e7548bULL;
  static const uint64_t static_value2 = 0x4e9c8076e7471dc3ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/lidar_get_frequency_infoResponse";
  }

  static const char* value(const ::test::lidar_get_frequency_infoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 frequency\n\
float64 minFrequency\n\
float64 maxFrequency\n\
\n\
";
  }

  static const char* value(const ::test::lidar_get_frequency_infoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frequency);
      stream.next(m.minFrequency);
      stream.next(m.maxFrequency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lidar_get_frequency_infoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::lidar_get_frequency_infoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::lidar_get_frequency_infoResponse_<ContainerAllocator>& v)
  {
    s << indent << "frequency: ";
    Printer<double>::stream(s, indent + "  ", v.frequency);
    s << indent << "minFrequency: ";
    Printer<double>::stream(s, indent + "  ", v.minFrequency);
    s << indent << "maxFrequency: ";
    Printer<double>::stream(s, indent + "  ", v.maxFrequency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_LIDAR_GET_FREQUENCY_INFORESPONSE_H
