// Generated by gencpp from file test/node_get_position.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_NODE_GET_POSITION_H
#define TEST_MESSAGE_NODE_GET_POSITION_H

#include <ros/service_traits.h>


#include <test/node_get_positionRequest.h>
#include <test/node_get_positionResponse.h>


namespace test
{

struct node_get_position
{

typedef node_get_positionRequest Request;
typedef node_get_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_position
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::node_get_position > {
  static const char* value()
  {
    return "a7fd7bab623637fe72e0ee179149fc41";
  }

  static const char* value(const ::test::node_get_position&) { return value(); }
};

template<>
struct DataType< ::test::node_get_position > {
  static const char* value()
  {
    return "test/node_get_position";
  }

  static const char* value(const ::test::node_get_position&) { return value(); }
};


// service_traits::MD5Sum< ::test::node_get_positionRequest> should match 
// service_traits::MD5Sum< ::test::node_get_position > 
template<>
struct MD5Sum< ::test::node_get_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::node_get_position >::value();
  }
  static const char* value(const ::test::node_get_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::node_get_positionRequest> should match 
// service_traits::DataType< ::test::node_get_position > 
template<>
struct DataType< ::test::node_get_positionRequest>
{
  static const char* value()
  {
    return DataType< ::test::node_get_position >::value();
  }
  static const char* value(const ::test::node_get_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::node_get_positionResponse> should match 
// service_traits::MD5Sum< ::test::node_get_position > 
template<>
struct MD5Sum< ::test::node_get_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::node_get_position >::value();
  }
  static const char* value(const ::test::node_get_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::node_get_positionResponse> should match 
// service_traits::DataType< ::test::node_get_position > 
template<>
struct DataType< ::test::node_get_positionResponse>
{
  static const char* value()
  {
    return DataType< ::test::node_get_position >::value();
  }
  static const char* value(const ::test::node_get_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_NODE_GET_POSITION_H
