// Generated by gencpp from file test/node_get_name.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_NODE_GET_NAME_H
#define TEST_MESSAGE_NODE_GET_NAME_H

#include <ros/service_traits.h>


#include <test/node_get_nameRequest.h>
#include <test/node_get_nameResponse.h>


namespace test
{

struct node_get_name
{

typedef node_get_nameRequest Request;
typedef node_get_nameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_name
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::node_get_name > {
  static const char* value()
  {
    return "51d3f5e9907c2b98d816acf3aad2e00e";
  }

  static const char* value(const ::test::node_get_name&) { return value(); }
};

template<>
struct DataType< ::test::node_get_name > {
  static const char* value()
  {
    return "test/node_get_name";
  }

  static const char* value(const ::test::node_get_name&) { return value(); }
};


// service_traits::MD5Sum< ::test::node_get_nameRequest> should match 
// service_traits::MD5Sum< ::test::node_get_name > 
template<>
struct MD5Sum< ::test::node_get_nameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::node_get_name >::value();
  }
  static const char* value(const ::test::node_get_nameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::node_get_nameRequest> should match 
// service_traits::DataType< ::test::node_get_name > 
template<>
struct DataType< ::test::node_get_nameRequest>
{
  static const char* value()
  {
    return DataType< ::test::node_get_name >::value();
  }
  static const char* value(const ::test::node_get_nameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::node_get_nameResponse> should match 
// service_traits::MD5Sum< ::test::node_get_name > 
template<>
struct MD5Sum< ::test::node_get_nameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::node_get_name >::value();
  }
  static const char* value(const ::test::node_get_nameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::node_get_nameResponse> should match 
// service_traits::DataType< ::test::node_get_name > 
template<>
struct DataType< ::test::node_get_nameResponse>
{
  static const char* value()
  {
    return DataType< ::test::node_get_name >::value();
  }
  static const char* value(const ::test::node_get_nameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_NODE_GET_NAME_H
