// Generated by gencpp from file test/pen_set_ink_color.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_PEN_SET_INK_COLOR_H
#define TEST_MESSAGE_PEN_SET_INK_COLOR_H

#include <ros/service_traits.h>


#include <test/pen_set_ink_colorRequest.h>
#include <test/pen_set_ink_colorResponse.h>


namespace test
{

struct pen_set_ink_color
{

typedef pen_set_ink_colorRequest Request;
typedef pen_set_ink_colorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pen_set_ink_color
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::pen_set_ink_color > {
  static const char* value()
  {
    return "7fde2080d14960fbc22200121684eabf";
  }

  static const char* value(const ::test::pen_set_ink_color&) { return value(); }
};

template<>
struct DataType< ::test::pen_set_ink_color > {
  static const char* value()
  {
    return "test/pen_set_ink_color";
  }

  static const char* value(const ::test::pen_set_ink_color&) { return value(); }
};


// service_traits::MD5Sum< ::test::pen_set_ink_colorRequest> should match 
// service_traits::MD5Sum< ::test::pen_set_ink_color > 
template<>
struct MD5Sum< ::test::pen_set_ink_colorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::pen_set_ink_color >::value();
  }
  static const char* value(const ::test::pen_set_ink_colorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::pen_set_ink_colorRequest> should match 
// service_traits::DataType< ::test::pen_set_ink_color > 
template<>
struct DataType< ::test::pen_set_ink_colorRequest>
{
  static const char* value()
  {
    return DataType< ::test::pen_set_ink_color >::value();
  }
  static const char* value(const ::test::pen_set_ink_colorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::pen_set_ink_colorResponse> should match 
// service_traits::MD5Sum< ::test::pen_set_ink_color > 
template<>
struct MD5Sum< ::test::pen_set_ink_colorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::pen_set_ink_color >::value();
  }
  static const char* value(const ::test::pen_set_ink_colorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::pen_set_ink_colorResponse> should match 
// service_traits::DataType< ::test::pen_set_ink_color > 
template<>
struct DataType< ::test::pen_set_ink_colorResponse>
{
  static const char* value()
  {
    return DataType< ::test::pen_set_ink_color >::value();
  }
  static const char* value(const ::test::pen_set_ink_colorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_PEN_SET_INK_COLOR_H
