// Generated by gencpp from file test/set_string.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_SET_STRING_H
#define TEST_MESSAGE_SET_STRING_H

#include <ros/service_traits.h>


#include <test/set_stringRequest.h>
#include <test/set_stringResponse.h>


namespace test
{

struct set_string
{

typedef set_stringRequest Request;
typedef set_stringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_string
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::set_string > {
  static const char* value()
  {
    return "0462bc0e878964615c49ad8ef45df667";
  }

  static const char* value(const ::test::set_string&) { return value(); }
};

template<>
struct DataType< ::test::set_string > {
  static const char* value()
  {
    return "test/set_string";
  }

  static const char* value(const ::test::set_string&) { return value(); }
};


// service_traits::MD5Sum< ::test::set_stringRequest> should match 
// service_traits::MD5Sum< ::test::set_string > 
template<>
struct MD5Sum< ::test::set_stringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::set_string >::value();
  }
  static const char* value(const ::test::set_stringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::set_stringRequest> should match 
// service_traits::DataType< ::test::set_string > 
template<>
struct DataType< ::test::set_stringRequest>
{
  static const char* value()
  {
    return DataType< ::test::set_string >::value();
  }
  static const char* value(const ::test::set_stringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::set_stringResponse> should match 
// service_traits::MD5Sum< ::test::set_string > 
template<>
struct MD5Sum< ::test::set_stringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::set_string >::value();
  }
  static const char* value(const ::test::set_stringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::set_stringResponse> should match 
// service_traits::DataType< ::test::set_string > 
template<>
struct DataType< ::test::set_stringResponse>
{
  static const char* value()
  {
    return DataType< ::test::set_string >::value();
  }
  static const char* value(const ::test::set_stringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_SET_STRING_H
