// Generated by gencpp from file test/supervisor_virtual_reality_headset_get_position.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_SUPERVISOR_VIRTUAL_REALITY_HEADSET_GET_POSITION_H
#define TEST_MESSAGE_SUPERVISOR_VIRTUAL_REALITY_HEADSET_GET_POSITION_H

#include <ros/service_traits.h>


#include <test/supervisor_virtual_reality_headset_get_positionRequest.h>
#include <test/supervisor_virtual_reality_headset_get_positionResponse.h>


namespace test
{

struct supervisor_virtual_reality_headset_get_position
{

typedef supervisor_virtual_reality_headset_get_positionRequest Request;
typedef supervisor_virtual_reality_headset_get_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct supervisor_virtual_reality_headset_get_position
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::supervisor_virtual_reality_headset_get_position > {
  static const char* value()
  {
    return "a1afe95e0bfbfc2663c9e2313392f01d";
  }

  static const char* value(const ::test::supervisor_virtual_reality_headset_get_position&) { return value(); }
};

template<>
struct DataType< ::test::supervisor_virtual_reality_headset_get_position > {
  static const char* value()
  {
    return "test/supervisor_virtual_reality_headset_get_position";
  }

  static const char* value(const ::test::supervisor_virtual_reality_headset_get_position&) { return value(); }
};


// service_traits::MD5Sum< ::test::supervisor_virtual_reality_headset_get_positionRequest> should match 
// service_traits::MD5Sum< ::test::supervisor_virtual_reality_headset_get_position > 
template<>
struct MD5Sum< ::test::supervisor_virtual_reality_headset_get_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::supervisor_virtual_reality_headset_get_position >::value();
  }
  static const char* value(const ::test::supervisor_virtual_reality_headset_get_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::supervisor_virtual_reality_headset_get_positionRequest> should match 
// service_traits::DataType< ::test::supervisor_virtual_reality_headset_get_position > 
template<>
struct DataType< ::test::supervisor_virtual_reality_headset_get_positionRequest>
{
  static const char* value()
  {
    return DataType< ::test::supervisor_virtual_reality_headset_get_position >::value();
  }
  static const char* value(const ::test::supervisor_virtual_reality_headset_get_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::supervisor_virtual_reality_headset_get_positionResponse> should match 
// service_traits::MD5Sum< ::test::supervisor_virtual_reality_headset_get_position > 
template<>
struct MD5Sum< ::test::supervisor_virtual_reality_headset_get_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::supervisor_virtual_reality_headset_get_position >::value();
  }
  static const char* value(const ::test::supervisor_virtual_reality_headset_get_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::supervisor_virtual_reality_headset_get_positionResponse> should match 
// service_traits::DataType< ::test::supervisor_virtual_reality_headset_get_position > 
template<>
struct DataType< ::test::supervisor_virtual_reality_headset_get_positionResponse>
{
  static const char* value()
  {
    return DataType< ::test::supervisor_virtual_reality_headset_get_position >::value();
  }
  static const char* value(const ::test::supervisor_virtual_reality_headset_get_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_SUPERVISOR_VIRTUAL_REALITY_HEADSET_GET_POSITION_H
