// Generated by gencpp from file test/display_draw_polygonRequest.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_DISPLAY_DRAW_POLYGONREQUEST_H
#define TEST_MESSAGE_DISPLAY_DRAW_POLYGONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct display_draw_polygonRequest_
{
  typedef display_draw_polygonRequest_<ContainerAllocator> Type;

  display_draw_polygonRequest_()
    : x()
    , y()
    , size(0)  {
    }
  display_draw_polygonRequest_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , size(0)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _x_type;
  _x_type x;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _y_type;
  _y_type y;

   typedef int32_t _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::test::display_draw_polygonRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::display_draw_polygonRequest_<ContainerAllocator> const> ConstPtr;

}; // struct display_draw_polygonRequest_

typedef ::test::display_draw_polygonRequest_<std::allocator<void> > display_draw_polygonRequest;

typedef boost::shared_ptr< ::test::display_draw_polygonRequest > display_draw_polygonRequestPtr;
typedef boost::shared_ptr< ::test::display_draw_polygonRequest const> display_draw_polygonRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::display_draw_polygonRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::display_draw_polygonRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'test': ['/home/nbhak/Desktop/test_ws/src/test/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test::display_draw_polygonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::display_draw_polygonRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::display_draw_polygonRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::display_draw_polygonRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::display_draw_polygonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::display_draw_polygonRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::display_draw_polygonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45140bfdfc5d8a44cc51b5a3d292b11c";
  }

  static const char* value(const ::test::display_draw_polygonRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45140bfdfc5d8a44ULL;
  static const uint64_t static_value2 = 0xcc51b5a3d292b11cULL;
};

template<class ContainerAllocator>
struct DataType< ::test::display_draw_polygonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/display_draw_polygonRequest";
  }

  static const char* value(const ::test::display_draw_polygonRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::display_draw_polygonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] x\n\
int32[] y\n\
int32 size\n\
";
  }

  static const char* value(const ::test::display_draw_polygonRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::display_draw_polygonRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct display_draw_polygonRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::display_draw_polygonRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::display_draw_polygonRequest_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_DISPLAY_DRAW_POLYGONREQUEST_H
