// Generated by gencpp from file test/field_set_string.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_FIELD_SET_STRING_H
#define TEST_MESSAGE_FIELD_SET_STRING_H

#include <ros/service_traits.h>


#include <test/field_set_stringRequest.h>
#include <test/field_set_stringResponse.h>


namespace test
{

struct field_set_string
{

typedef field_set_stringRequest Request;
typedef field_set_stringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_set_string
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::field_set_string > {
  static const char* value()
  {
    return "a84b2f7623a3316b5dc8470fcbf631fd";
  }

  static const char* value(const ::test::field_set_string&) { return value(); }
};

template<>
struct DataType< ::test::field_set_string > {
  static const char* value()
  {
    return "test/field_set_string";
  }

  static const char* value(const ::test::field_set_string&) { return value(); }
};


// service_traits::MD5Sum< ::test::field_set_stringRequest> should match 
// service_traits::MD5Sum< ::test::field_set_string > 
template<>
struct MD5Sum< ::test::field_set_stringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::field_set_string >::value();
  }
  static const char* value(const ::test::field_set_stringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::field_set_stringRequest> should match 
// service_traits::DataType< ::test::field_set_string > 
template<>
struct DataType< ::test::field_set_stringRequest>
{
  static const char* value()
  {
    return DataType< ::test::field_set_string >::value();
  }
  static const char* value(const ::test::field_set_stringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::field_set_stringResponse> should match 
// service_traits::MD5Sum< ::test::field_set_string > 
template<>
struct MD5Sum< ::test::field_set_stringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::field_set_string >::value();
  }
  static const char* value(const ::test::field_set_stringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::field_set_stringResponse> should match 
// service_traits::DataType< ::test::field_set_string > 
template<>
struct DataType< ::test::field_set_stringResponse>
{
  static const char* value()
  {
    return DataType< ::test::field_set_string >::value();
  }
  static const char* value(const ::test::field_set_stringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_FIELD_SET_STRING_H
