// Generated by gencpp from file test/field_set_vec2f.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_FIELD_SET_VEC2F_H
#define TEST_MESSAGE_FIELD_SET_VEC2F_H

#include <ros/service_traits.h>


#include <test/field_set_vec2fRequest.h>
#include <test/field_set_vec2fResponse.h>


namespace test
{

struct field_set_vec2f
{

typedef field_set_vec2fRequest Request;
typedef field_set_vec2fResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_set_vec2f
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::field_set_vec2f > {
  static const char* value()
  {
    return "e0edef5860d282e4d35ef264e28feecc";
  }

  static const char* value(const ::test::field_set_vec2f&) { return value(); }
};

template<>
struct DataType< ::test::field_set_vec2f > {
  static const char* value()
  {
    return "test/field_set_vec2f";
  }

  static const char* value(const ::test::field_set_vec2f&) { return value(); }
};


// service_traits::MD5Sum< ::test::field_set_vec2fRequest> should match 
// service_traits::MD5Sum< ::test::field_set_vec2f > 
template<>
struct MD5Sum< ::test::field_set_vec2fRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::field_set_vec2f >::value();
  }
  static const char* value(const ::test::field_set_vec2fRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::field_set_vec2fRequest> should match 
// service_traits::DataType< ::test::field_set_vec2f > 
template<>
struct DataType< ::test::field_set_vec2fRequest>
{
  static const char* value()
  {
    return DataType< ::test::field_set_vec2f >::value();
  }
  static const char* value(const ::test::field_set_vec2fRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::field_set_vec2fResponse> should match 
// service_traits::MD5Sum< ::test::field_set_vec2f > 
template<>
struct MD5Sum< ::test::field_set_vec2fResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::field_set_vec2f >::value();
  }
  static const char* value(const ::test::field_set_vec2fResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::field_set_vec2fResponse> should match 
// service_traits::DataType< ::test::field_set_vec2f > 
template<>
struct DataType< ::test::field_set_vec2fResponse>
{
  static const char* value()
  {
    return DataType< ::test::field_set_vec2f >::value();
  }
  static const char* value(const ::test::field_set_vec2fResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_FIELD_SET_VEC2F_H
