// Generated by gencpp from file test/field_get_type.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_FIELD_GET_TYPE_H
#define TEST_MESSAGE_FIELD_GET_TYPE_H

#include <ros/service_traits.h>


#include <test/field_get_typeRequest.h>
#include <test/field_get_typeResponse.h>


namespace test
{

struct field_get_type
{

typedef field_get_typeRequest Request;
typedef field_get_typeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_get_type
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::field_get_type > {
  static const char* value()
  {
    return "0455d6401eca2603b986dbfe1a1e17b4";
  }

  static const char* value(const ::test::field_get_type&) { return value(); }
};

template<>
struct DataType< ::test::field_get_type > {
  static const char* value()
  {
    return "test/field_get_type";
  }

  static const char* value(const ::test::field_get_type&) { return value(); }
};


// service_traits::MD5Sum< ::test::field_get_typeRequest> should match 
// service_traits::MD5Sum< ::test::field_get_type > 
template<>
struct MD5Sum< ::test::field_get_typeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::field_get_type >::value();
  }
  static const char* value(const ::test::field_get_typeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::field_get_typeRequest> should match 
// service_traits::DataType< ::test::field_get_type > 
template<>
struct DataType< ::test::field_get_typeRequest>
{
  static const char* value()
  {
    return DataType< ::test::field_get_type >::value();
  }
  static const char* value(const ::test::field_get_typeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::field_get_typeResponse> should match 
// service_traits::MD5Sum< ::test::field_get_type > 
template<>
struct MD5Sum< ::test::field_get_typeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::field_get_type >::value();
  }
  static const char* value(const ::test::field_get_typeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::field_get_typeResponse> should match 
// service_traits::DataType< ::test::field_get_type > 
template<>
struct DataType< ::test::field_get_typeResponse>
{
  static const char* value()
  {
    return DataType< ::test::field_get_type >::value();
  }
  static const char* value(const ::test::field_get_typeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_FIELD_GET_TYPE_H
