// Generated by gencpp from file test/field_import_node_from_string.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_FIELD_IMPORT_NODE_FROM_STRING_H
#define TEST_MESSAGE_FIELD_IMPORT_NODE_FROM_STRING_H

#include <ros/service_traits.h>


#include <test/field_import_node_from_stringRequest.h>
#include <test/field_import_node_from_stringResponse.h>


namespace test
{

struct field_import_node_from_string
{

typedef field_import_node_from_stringRequest Request;
typedef field_import_node_from_stringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_import_node_from_string
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::field_import_node_from_string > {
  static const char* value()
  {
    return "f47a09684279b85c2c8ae161048ce7d0";
  }

  static const char* value(const ::test::field_import_node_from_string&) { return value(); }
};

template<>
struct DataType< ::test::field_import_node_from_string > {
  static const char* value()
  {
    return "test/field_import_node_from_string";
  }

  static const char* value(const ::test::field_import_node_from_string&) { return value(); }
};


// service_traits::MD5Sum< ::test::field_import_node_from_stringRequest> should match 
// service_traits::MD5Sum< ::test::field_import_node_from_string > 
template<>
struct MD5Sum< ::test::field_import_node_from_stringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::field_import_node_from_string >::value();
  }
  static const char* value(const ::test::field_import_node_from_stringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::field_import_node_from_stringRequest> should match 
// service_traits::DataType< ::test::field_import_node_from_string > 
template<>
struct DataType< ::test::field_import_node_from_stringRequest>
{
  static const char* value()
  {
    return DataType< ::test::field_import_node_from_string >::value();
  }
  static const char* value(const ::test::field_import_node_from_stringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::field_import_node_from_stringResponse> should match 
// service_traits::MD5Sum< ::test::field_import_node_from_string > 
template<>
struct MD5Sum< ::test::field_import_node_from_stringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::field_import_node_from_string >::value();
  }
  static const char* value(const ::test::field_import_node_from_stringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::field_import_node_from_stringResponse> should match 
// service_traits::DataType< ::test::field_import_node_from_string > 
template<>
struct DataType< ::test::field_import_node_from_stringResponse>
{
  static const char* value()
  {
    return DataType< ::test::field_import_node_from_string >::value();
  }
  static const char* value(const ::test::field_import_node_from_stringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_FIELD_IMPORT_NODE_FROM_STRING_H
