// Generated by gencpp from file test/field_set_float.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_FIELD_SET_FLOAT_H
#define TEST_MESSAGE_FIELD_SET_FLOAT_H

#include <ros/service_traits.h>


#include <test/field_set_floatRequest.h>
#include <test/field_set_floatResponse.h>


namespace test
{

struct field_set_float
{

typedef field_set_floatRequest Request;
typedef field_set_floatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_set_float
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::field_set_float > {
  static const char* value()
  {
    return "4e40976b84f091a5cb0ce60a329c40a3";
  }

  static const char* value(const ::test::field_set_float&) { return value(); }
};

template<>
struct DataType< ::test::field_set_float > {
  static const char* value()
  {
    return "test/field_set_float";
  }

  static const char* value(const ::test::field_set_float&) { return value(); }
};


// service_traits::MD5Sum< ::test::field_set_floatRequest> should match 
// service_traits::MD5Sum< ::test::field_set_float > 
template<>
struct MD5Sum< ::test::field_set_floatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::field_set_float >::value();
  }
  static const char* value(const ::test::field_set_floatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::field_set_floatRequest> should match 
// service_traits::DataType< ::test::field_set_float > 
template<>
struct DataType< ::test::field_set_floatRequest>
{
  static const char* value()
  {
    return DataType< ::test::field_set_float >::value();
  }
  static const char* value(const ::test::field_set_floatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::field_set_floatResponse> should match 
// service_traits::MD5Sum< ::test::field_set_float > 
template<>
struct MD5Sum< ::test::field_set_floatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::field_set_float >::value();
  }
  static const char* value(const ::test::field_set_floatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::field_set_floatResponse> should match 
// service_traits::DataType< ::test::field_set_float > 
template<>
struct DataType< ::test::field_set_floatResponse>
{
  static const char* value()
  {
    return DataType< ::test::field_set_float >::value();
  }
  static const char* value(const ::test::field_set_floatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_FIELD_SET_FLOAT_H
