// Generated by gencpp from file test/get_float_arrayResponse.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_GET_FLOAT_ARRAYRESPONSE_H
#define TEST_MESSAGE_GET_FLOAT_ARRAYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct get_float_arrayResponse_
{
  typedef get_float_arrayResponse_<ContainerAllocator> Type;

  get_float_arrayResponse_()
    : value()  {
    }
  get_float_arrayResponse_(const ContainerAllocator& _alloc)
    : value(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::test::get_float_arrayResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::get_float_arrayResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_float_arrayResponse_

typedef ::test::get_float_arrayResponse_<std::allocator<void> > get_float_arrayResponse;

typedef boost::shared_ptr< ::test::get_float_arrayResponse > get_float_arrayResponsePtr;
typedef boost::shared_ptr< ::test::get_float_arrayResponse const> get_float_arrayResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::get_float_arrayResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::get_float_arrayResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'test': ['/home/nbhak/Desktop/test_ws/src/test/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test::get_float_arrayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::get_float_arrayResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::get_float_arrayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::get_float_arrayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::get_float_arrayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::get_float_arrayResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::get_float_arrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0db98d790b5b039efb61505385ae8369";
  }

  static const char* value(const ::test::get_float_arrayResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0db98d790b5b039eULL;
  static const uint64_t static_value2 = 0xfb61505385ae8369ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::get_float_arrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/get_float_arrayResponse";
  }

  static const char* value(const ::test::get_float_arrayResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::get_float_arrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] value\n\
\n\
";
  }

  static const char* value(const ::test::get_float_arrayResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::get_float_arrayResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_float_arrayResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::get_float_arrayResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::get_float_arrayResponse_<ContainerAllocator>& v)
  {
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_GET_FLOAT_ARRAYRESPONSE_H
