// Generated by gencpp from file test/lidar_get_layer_point_cloudRequest.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_LIDAR_GET_LAYER_POINT_CLOUDREQUEST_H
#define TEST_MESSAGE_LIDAR_GET_LAYER_POINT_CLOUDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct lidar_get_layer_point_cloudRequest_
{
  typedef lidar_get_layer_point_cloudRequest_<ContainerAllocator> Type;

  lidar_get_layer_point_cloudRequest_()
    : layer(0)  {
    }
  lidar_get_layer_point_cloudRequest_(const ContainerAllocator& _alloc)
    : layer(0)  {
  (void)_alloc;
    }



   typedef int32_t _layer_type;
  _layer_type layer;





  typedef boost::shared_ptr< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> const> ConstPtr;

}; // struct lidar_get_layer_point_cloudRequest_

typedef ::test::lidar_get_layer_point_cloudRequest_<std::allocator<void> > lidar_get_layer_point_cloudRequest;

typedef boost::shared_ptr< ::test::lidar_get_layer_point_cloudRequest > lidar_get_layer_point_cloudRequestPtr;
typedef boost::shared_ptr< ::test::lidar_get_layer_point_cloudRequest const> lidar_get_layer_point_cloudRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test': ['/home/nbhak/Desktop/test_ws/src/test/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d6c1c0236296850b6361a672e8a61c4";
  }

  static const char* value(const ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d6c1c0236296850ULL;
  static const uint64_t static_value2 = 0xb6361a672e8a61c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/lidar_get_layer_point_cloudRequest";
  }

  static const char* value(const ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 layer\n\
";
  }

  static const char* value(const ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.layer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lidar_get_layer_point_cloudRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::lidar_get_layer_point_cloudRequest_<ContainerAllocator>& v)
  {
    s << indent << "layer: ";
    Printer<int32_t>::stream(s, indent + "  ", v.layer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_LIDAR_GET_LAYER_POINT_CLOUDREQUEST_H
