// Generated by gencpp from file test/node_get_velocity.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_NODE_GET_VELOCITY_H
#define TEST_MESSAGE_NODE_GET_VELOCITY_H

#include <ros/service_traits.h>


#include <test/node_get_velocityRequest.h>
#include <test/node_get_velocityResponse.h>


namespace test
{

struct node_get_velocity
{

typedef node_get_velocityRequest Request;
typedef node_get_velocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_velocity
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::node_get_velocity > {
  static const char* value()
  {
    return "f50dcf3848a1b2dce54e5fbe9ff12eac";
  }

  static const char* value(const ::test::node_get_velocity&) { return value(); }
};

template<>
struct DataType< ::test::node_get_velocity > {
  static const char* value()
  {
    return "test/node_get_velocity";
  }

  static const char* value(const ::test::node_get_velocity&) { return value(); }
};


// service_traits::MD5Sum< ::test::node_get_velocityRequest> should match 
// service_traits::MD5Sum< ::test::node_get_velocity > 
template<>
struct MD5Sum< ::test::node_get_velocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::node_get_velocity >::value();
  }
  static const char* value(const ::test::node_get_velocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::node_get_velocityRequest> should match 
// service_traits::DataType< ::test::node_get_velocity > 
template<>
struct DataType< ::test::node_get_velocityRequest>
{
  static const char* value()
  {
    return DataType< ::test::node_get_velocity >::value();
  }
  static const char* value(const ::test::node_get_velocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::node_get_velocityResponse> should match 
// service_traits::MD5Sum< ::test::node_get_velocity > 
template<>
struct MD5Sum< ::test::node_get_velocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::node_get_velocity >::value();
  }
  static const char* value(const ::test::node_get_velocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::node_get_velocityResponse> should match 
// service_traits::DataType< ::test::node_get_velocity > 
template<>
struct DataType< ::test::node_get_velocityResponse>
{
  static const char* value()
  {
    return DataType< ::test::node_get_velocity >::value();
  }
  static const char* value(const ::test::node_get_velocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_NODE_GET_VELOCITY_H
