// Generated by gencpp from file test/node_remove.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_NODE_REMOVE_H
#define TEST_MESSAGE_NODE_REMOVE_H

#include <ros/service_traits.h>


#include <test/node_removeRequest.h>
#include <test/node_removeResponse.h>


namespace test
{

struct node_remove
{

typedef node_removeRequest Request;
typedef node_removeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_remove
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::node_remove > {
  static const char* value()
  {
    return "594d3b785623c78d3382c6628faa0f8c";
  }

  static const char* value(const ::test::node_remove&) { return value(); }
};

template<>
struct DataType< ::test::node_remove > {
  static const char* value()
  {
    return "test/node_remove";
  }

  static const char* value(const ::test::node_remove&) { return value(); }
};


// service_traits::MD5Sum< ::test::node_removeRequest> should match 
// service_traits::MD5Sum< ::test::node_remove > 
template<>
struct MD5Sum< ::test::node_removeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::node_remove >::value();
  }
  static const char* value(const ::test::node_removeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::node_removeRequest> should match 
// service_traits::DataType< ::test::node_remove > 
template<>
struct DataType< ::test::node_removeRequest>
{
  static const char* value()
  {
    return DataType< ::test::node_remove >::value();
  }
  static const char* value(const ::test::node_removeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::node_removeResponse> should match 
// service_traits::MD5Sum< ::test::node_remove > 
template<>
struct MD5Sum< ::test::node_removeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::node_remove >::value();
  }
  static const char* value(const ::test::node_removeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::node_removeResponse> should match 
// service_traits::DataType< ::test::node_remove > 
template<>
struct DataType< ::test::node_removeResponse>
{
  static const char* value()
  {
    return DataType< ::test::node_remove >::value();
  }
  static const char* value(const ::test::node_removeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_NODE_REMOVE_H
