// Generated by gencpp from file test/set_float.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_SET_FLOAT_H
#define TEST_MESSAGE_SET_FLOAT_H

#include <ros/service_traits.h>


#include <test/set_floatRequest.h>
#include <test/set_floatResponse.h>


namespace test
{

struct set_float
{

typedef set_floatRequest Request;
typedef set_floatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_float
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::set_float > {
  static const char* value()
  {
    return "0f0509b4253b73657cb37e93f4f2960c";
  }

  static const char* value(const ::test::set_float&) { return value(); }
};

template<>
struct DataType< ::test::set_float > {
  static const char* value()
  {
    return "test/set_float";
  }

  static const char* value(const ::test::set_float&) { return value(); }
};


// service_traits::MD5Sum< ::test::set_floatRequest> should match 
// service_traits::MD5Sum< ::test::set_float > 
template<>
struct MD5Sum< ::test::set_floatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::set_float >::value();
  }
  static const char* value(const ::test::set_floatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::set_floatRequest> should match 
// service_traits::DataType< ::test::set_float > 
template<>
struct DataType< ::test::set_floatRequest>
{
  static const char* value()
  {
    return DataType< ::test::set_float >::value();
  }
  static const char* value(const ::test::set_floatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::set_floatResponse> should match 
// service_traits::MD5Sum< ::test::set_float > 
template<>
struct MD5Sum< ::test::set_floatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::set_float >::value();
  }
  static const char* value(const ::test::set_floatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::set_floatResponse> should match 
// service_traits::DataType< ::test::set_float > 
template<>
struct DataType< ::test::set_floatResponse>
{
  static const char* value()
  {
    return DataType< ::test::set_float >::value();
  }
  static const char* value(const ::test::set_floatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_SET_FLOAT_H
