// Generated by gencpp from file test/set_bool.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_SET_BOOL_H
#define TEST_MESSAGE_SET_BOOL_H

#include <ros/service_traits.h>


#include <test/set_boolRequest.h>
#include <test/set_boolResponse.h>


namespace test
{

struct set_bool
{

typedef set_boolRequest Request;
typedef set_boolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_bool
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::set_bool > {
  static const char* value()
  {
    return "24a0f9fd764459b7e35d04a0dd83dd11";
  }

  static const char* value(const ::test::set_bool&) { return value(); }
};

template<>
struct DataType< ::test::set_bool > {
  static const char* value()
  {
    return "test/set_bool";
  }

  static const char* value(const ::test::set_bool&) { return value(); }
};


// service_traits::MD5Sum< ::test::set_boolRequest> should match 
// service_traits::MD5Sum< ::test::set_bool > 
template<>
struct MD5Sum< ::test::set_boolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::set_bool >::value();
  }
  static const char* value(const ::test::set_boolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::set_boolRequest> should match 
// service_traits::DataType< ::test::set_bool > 
template<>
struct DataType< ::test::set_boolRequest>
{
  static const char* value()
  {
    return DataType< ::test::set_bool >::value();
  }
  static const char* value(const ::test::set_boolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::set_boolResponse> should match 
// service_traits::MD5Sum< ::test::set_bool > 
template<>
struct MD5Sum< ::test::set_boolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::set_bool >::value();
  }
  static const char* value(const ::test::set_boolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::set_boolResponse> should match 
// service_traits::DataType< ::test::set_bool > 
template<>
struct DataType< ::test::set_boolResponse>
{
  static const char* value()
  {
    return DataType< ::test::set_bool >::value();
  }
  static const char* value(const ::test::set_boolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_SET_BOOL_H
