// Generated by gencpp from file test/set_int.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_SET_INT_H
#define TEST_MESSAGE_SET_INT_H

#include <ros/service_traits.h>


#include <test/set_intRequest.h>
#include <test/set_intResponse.h>


namespace test
{

struct set_int
{

typedef set_intRequest Request;
typedef set_intResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_int
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::set_int > {
  static const char* value()
  {
    return "bc437afb45673379bdb9f299f9cbbc9e";
  }

  static const char* value(const ::test::set_int&) { return value(); }
};

template<>
struct DataType< ::test::set_int > {
  static const char* value()
  {
    return "test/set_int";
  }

  static const char* value(const ::test::set_int&) { return value(); }
};


// service_traits::MD5Sum< ::test::set_intRequest> should match 
// service_traits::MD5Sum< ::test::set_int > 
template<>
struct MD5Sum< ::test::set_intRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::set_int >::value();
  }
  static const char* value(const ::test::set_intRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::set_intRequest> should match 
// service_traits::DataType< ::test::set_int > 
template<>
struct DataType< ::test::set_intRequest>
{
  static const char* value()
  {
    return DataType< ::test::set_int >::value();
  }
  static const char* value(const ::test::set_intRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::set_intResponse> should match 
// service_traits::MD5Sum< ::test::set_int > 
template<>
struct MD5Sum< ::test::set_intResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::set_int >::value();
  }
  static const char* value(const ::test::set_intResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::set_intResponse> should match 
// service_traits::DataType< ::test::set_int > 
template<>
struct DataType< ::test::set_intResponse>
{
  static const char* value()
  {
    return DataType< ::test::set_int >::value();
  }
  static const char* value(const ::test::set_intResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_SET_INT_H
