// Generated by gencpp from file test/set_float_array.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_SET_FLOAT_ARRAY_H
#define TEST_MESSAGE_SET_FLOAT_ARRAY_H

#include <ros/service_traits.h>


#include <test/set_float_arrayRequest.h>
#include <test/set_float_arrayResponse.h>


namespace test
{

struct set_float_array
{

typedef set_float_arrayRequest Request;
typedef set_float_arrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_float_array
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::set_float_array > {
  static const char* value()
  {
    return "0fcc5d2c24929b6dbbf415b9579ddce4";
  }

  static const char* value(const ::test::set_float_array&) { return value(); }
};

template<>
struct DataType< ::test::set_float_array > {
  static const char* value()
  {
    return "test/set_float_array";
  }

  static const char* value(const ::test::set_float_array&) { return value(); }
};


// service_traits::MD5Sum< ::test::set_float_arrayRequest> should match 
// service_traits::MD5Sum< ::test::set_float_array > 
template<>
struct MD5Sum< ::test::set_float_arrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::set_float_array >::value();
  }
  static const char* value(const ::test::set_float_arrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::set_float_arrayRequest> should match 
// service_traits::DataType< ::test::set_float_array > 
template<>
struct DataType< ::test::set_float_arrayRequest>
{
  static const char* value()
  {
    return DataType< ::test::set_float_array >::value();
  }
  static const char* value(const ::test::set_float_arrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::set_float_arrayResponse> should match 
// service_traits::MD5Sum< ::test::set_float_array > 
template<>
struct MD5Sum< ::test::set_float_arrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::set_float_array >::value();
  }
  static const char* value(const ::test::set_float_arrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::set_float_arrayResponse> should match 
// service_traits::DataType< ::test::set_float_array > 
template<>
struct DataType< ::test::set_float_arrayResponse>
{
  static const char* value()
  {
    return DataType< ::test::set_float_array >::value();
  }
  static const char* value(const ::test::set_float_arrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_SET_FLOAT_ARRAY_H
