// Generated by gencpp from file test/speaker_speak.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_SPEAKER_SPEAK_H
#define TEST_MESSAGE_SPEAKER_SPEAK_H

#include <ros/service_traits.h>


#include <test/speaker_speakRequest.h>
#include <test/speaker_speakResponse.h>


namespace test
{

struct speaker_speak
{

typedef speaker_speakRequest Request;
typedef speaker_speakResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct speaker_speak
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::speaker_speak > {
  static const char* value()
  {
    return "bc987d1a1839d594218b7c1d6a77ba5e";
  }

  static const char* value(const ::test::speaker_speak&) { return value(); }
};

template<>
struct DataType< ::test::speaker_speak > {
  static const char* value()
  {
    return "test/speaker_speak";
  }

  static const char* value(const ::test::speaker_speak&) { return value(); }
};


// service_traits::MD5Sum< ::test::speaker_speakRequest> should match 
// service_traits::MD5Sum< ::test::speaker_speak > 
template<>
struct MD5Sum< ::test::speaker_speakRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::speaker_speak >::value();
  }
  static const char* value(const ::test::speaker_speakRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::speaker_speakRequest> should match 
// service_traits::DataType< ::test::speaker_speak > 
template<>
struct DataType< ::test::speaker_speakRequest>
{
  static const char* value()
  {
    return DataType< ::test::speaker_speak >::value();
  }
  static const char* value(const ::test::speaker_speakRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::speaker_speakResponse> should match 
// service_traits::MD5Sum< ::test::speaker_speak > 
template<>
struct MD5Sum< ::test::speaker_speakResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::speaker_speak >::value();
  }
  static const char* value(const ::test::speaker_speakResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::speaker_speakResponse> should match 
// service_traits::DataType< ::test::speaker_speak > 
template<>
struct DataType< ::test::speaker_speakResponse>
{
  static const char* value()
  {
    return DataType< ::test::speaker_speak >::value();
  }
  static const char* value(const ::test::speaker_speakResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_SPEAKER_SPEAK_H
