// Generated by gencpp from file test/speaker_is_sound_playing.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_SPEAKER_IS_SOUND_PLAYING_H
#define TEST_MESSAGE_SPEAKER_IS_SOUND_PLAYING_H

#include <ros/service_traits.h>


#include <test/speaker_is_sound_playingRequest.h>
#include <test/speaker_is_sound_playingResponse.h>


namespace test
{

struct speaker_is_sound_playing
{

typedef speaker_is_sound_playingRequest Request;
typedef speaker_is_sound_playingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct speaker_is_sound_playing
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::speaker_is_sound_playing > {
  static const char* value()
  {
    return "5e90e3a791904b68b561b7067a8d366b";
  }

  static const char* value(const ::test::speaker_is_sound_playing&) { return value(); }
};

template<>
struct DataType< ::test::speaker_is_sound_playing > {
  static const char* value()
  {
    return "test/speaker_is_sound_playing";
  }

  static const char* value(const ::test::speaker_is_sound_playing&) { return value(); }
};


// service_traits::MD5Sum< ::test::speaker_is_sound_playingRequest> should match 
// service_traits::MD5Sum< ::test::speaker_is_sound_playing > 
template<>
struct MD5Sum< ::test::speaker_is_sound_playingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::speaker_is_sound_playing >::value();
  }
  static const char* value(const ::test::speaker_is_sound_playingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::speaker_is_sound_playingRequest> should match 
// service_traits::DataType< ::test::speaker_is_sound_playing > 
template<>
struct DataType< ::test::speaker_is_sound_playingRequest>
{
  static const char* value()
  {
    return DataType< ::test::speaker_is_sound_playing >::value();
  }
  static const char* value(const ::test::speaker_is_sound_playingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::speaker_is_sound_playingResponse> should match 
// service_traits::MD5Sum< ::test::speaker_is_sound_playing > 
template<>
struct MD5Sum< ::test::speaker_is_sound_playingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::speaker_is_sound_playing >::value();
  }
  static const char* value(const ::test::speaker_is_sound_playingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::speaker_is_sound_playingResponse> should match 
// service_traits::DataType< ::test::speaker_is_sound_playing > 
template<>
struct DataType< ::test::speaker_is_sound_playingResponse>
{
  static const char* value()
  {
    return DataType< ::test::speaker_is_sound_playing >::value();
  }
  static const char* value(const ::test::speaker_is_sound_playingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_SPEAKER_IS_SOUND_PLAYING_H
