// Generated by gencpp from file test/speaker_play_sound.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_SPEAKER_PLAY_SOUND_H
#define TEST_MESSAGE_SPEAKER_PLAY_SOUND_H

#include <ros/service_traits.h>


#include <test/speaker_play_soundRequest.h>
#include <test/speaker_play_soundResponse.h>


namespace test
{

struct speaker_play_sound
{

typedef speaker_play_soundRequest Request;
typedef speaker_play_soundResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct speaker_play_sound
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::speaker_play_sound > {
  static const char* value()
  {
    return "9c17e6742fccca17f3542e68a9800dd3";
  }

  static const char* value(const ::test::speaker_play_sound&) { return value(); }
};

template<>
struct DataType< ::test::speaker_play_sound > {
  static const char* value()
  {
    return "test/speaker_play_sound";
  }

  static const char* value(const ::test::speaker_play_sound&) { return value(); }
};


// service_traits::MD5Sum< ::test::speaker_play_soundRequest> should match 
// service_traits::MD5Sum< ::test::speaker_play_sound > 
template<>
struct MD5Sum< ::test::speaker_play_soundRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::speaker_play_sound >::value();
  }
  static const char* value(const ::test::speaker_play_soundRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::speaker_play_soundRequest> should match 
// service_traits::DataType< ::test::speaker_play_sound > 
template<>
struct DataType< ::test::speaker_play_soundRequest>
{
  static const char* value()
  {
    return DataType< ::test::speaker_play_sound >::value();
  }
  static const char* value(const ::test::speaker_play_soundRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::speaker_play_soundResponse> should match 
// service_traits::MD5Sum< ::test::speaker_play_sound > 
template<>
struct MD5Sum< ::test::speaker_play_soundResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::speaker_play_sound >::value();
  }
  static const char* value(const ::test::speaker_play_soundResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::speaker_play_soundResponse> should match 
// service_traits::DataType< ::test::speaker_play_sound > 
template<>
struct DataType< ::test::speaker_play_soundResponse>
{
  static const char* value()
  {
    return DataType< ::test::speaker_play_sound >::value();
  }
  static const char* value(const ::test::speaker_play_soundResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_SPEAKER_PLAY_SOUND_H
