// Generated by gencpp from file test/supervisor_get_from_id.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_SUPERVISOR_GET_FROM_ID_H
#define TEST_MESSAGE_SUPERVISOR_GET_FROM_ID_H

#include <ros/service_traits.h>


#include <test/supervisor_get_from_idRequest.h>
#include <test/supervisor_get_from_idResponse.h>


namespace test
{

struct supervisor_get_from_id
{

typedef supervisor_get_from_idRequest Request;
typedef supervisor_get_from_idResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct supervisor_get_from_id
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::supervisor_get_from_id > {
  static const char* value()
  {
    return "398e4930ac99b6ae9bc51fa66b0d9846";
  }

  static const char* value(const ::test::supervisor_get_from_id&) { return value(); }
};

template<>
struct DataType< ::test::supervisor_get_from_id > {
  static const char* value()
  {
    return "test/supervisor_get_from_id";
  }

  static const char* value(const ::test::supervisor_get_from_id&) { return value(); }
};


// service_traits::MD5Sum< ::test::supervisor_get_from_idRequest> should match 
// service_traits::MD5Sum< ::test::supervisor_get_from_id > 
template<>
struct MD5Sum< ::test::supervisor_get_from_idRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::supervisor_get_from_id >::value();
  }
  static const char* value(const ::test::supervisor_get_from_idRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::supervisor_get_from_idRequest> should match 
// service_traits::DataType< ::test::supervisor_get_from_id > 
template<>
struct DataType< ::test::supervisor_get_from_idRequest>
{
  static const char* value()
  {
    return DataType< ::test::supervisor_get_from_id >::value();
  }
  static const char* value(const ::test::supervisor_get_from_idRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::supervisor_get_from_idResponse> should match 
// service_traits::MD5Sum< ::test::supervisor_get_from_id > 
template<>
struct MD5Sum< ::test::supervisor_get_from_idResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::supervisor_get_from_id >::value();
  }
  static const char* value(const ::test::supervisor_get_from_idResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::supervisor_get_from_idResponse> should match 
// service_traits::DataType< ::test::supervisor_get_from_id > 
template<>
struct DataType< ::test::supervisor_get_from_idResponse>
{
  static const char* value()
  {
    return DataType< ::test::supervisor_get_from_id >::value();
  }
  static const char* value(const ::test::supervisor_get_from_idResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_SUPERVISOR_GET_FROM_ID_H
