// Generated by gencpp from file test/display_image_newRequest.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_DISPLAY_IMAGE_NEWREQUEST_H
#define TEST_MESSAGE_DISPLAY_IMAGE_NEWREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct display_image_newRequest_
{
  typedef display_image_newRequest_<ContainerAllocator> Type;

  display_image_newRequest_()
    : width(0)
    , height(0)
    , data()
    , format(0)  {
    }
  display_image_newRequest_(const ContainerAllocator& _alloc)
    : width(0)
    , height(0)
    , data(_alloc)
    , format(0)  {
  (void)_alloc;
    }



   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;

   typedef int32_t _format_type;
  _format_type format;





  typedef boost::shared_ptr< ::test::display_image_newRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::display_image_newRequest_<ContainerAllocator> const> ConstPtr;

}; // struct display_image_newRequest_

typedef ::test::display_image_newRequest_<std::allocator<void> > display_image_newRequest;

typedef boost::shared_ptr< ::test::display_image_newRequest > display_image_newRequestPtr;
typedef boost::shared_ptr< ::test::display_image_newRequest const> display_image_newRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::display_image_newRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::display_image_newRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'test': ['/home/nbhak/Desktop/test_ws/src/test/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test::display_image_newRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::display_image_newRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::display_image_newRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::display_image_newRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::display_image_newRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::display_image_newRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::display_image_newRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ca26e28adfc59a4ed4a4edca51b7548";
  }

  static const char* value(const ::test::display_image_newRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ca26e28adfc59a4ULL;
  static const uint64_t static_value2 = 0xed4a4edca51b7548ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::display_image_newRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/display_image_newRequest";
  }

  static const char* value(const ::test::display_image_newRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::display_image_newRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 width\n\
int32 height\n\
char[] data\n\
int32 format\n\
";
  }

  static const char* value(const ::test::display_image_newRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::display_image_newRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.data);
      stream.next(m.format);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct display_image_newRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::display_image_newRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::display_image_newRequest_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "format: ";
    Printer<int32_t>::stream(s, indent + "  ", v.format);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_DISPLAY_IMAGE_NEWREQUEST_H
