// Generated by gencpp from file test/display_draw_pixel.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_DISPLAY_DRAW_PIXEL_H
#define TEST_MESSAGE_DISPLAY_DRAW_PIXEL_H

#include <ros/service_traits.h>


#include <test/display_draw_pixelRequest.h>
#include <test/display_draw_pixelResponse.h>


namespace test
{

struct display_draw_pixel
{

typedef display_draw_pixelRequest Request;
typedef display_draw_pixelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_draw_pixel
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::display_draw_pixel > {
  static const char* value()
  {
    return "e8e87fb7b87ab83a24bea771b7fc11df";
  }

  static const char* value(const ::test::display_draw_pixel&) { return value(); }
};

template<>
struct DataType< ::test::display_draw_pixel > {
  static const char* value()
  {
    return "test/display_draw_pixel";
  }

  static const char* value(const ::test::display_draw_pixel&) { return value(); }
};


// service_traits::MD5Sum< ::test::display_draw_pixelRequest> should match 
// service_traits::MD5Sum< ::test::display_draw_pixel > 
template<>
struct MD5Sum< ::test::display_draw_pixelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::display_draw_pixel >::value();
  }
  static const char* value(const ::test::display_draw_pixelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::display_draw_pixelRequest> should match 
// service_traits::DataType< ::test::display_draw_pixel > 
template<>
struct DataType< ::test::display_draw_pixelRequest>
{
  static const char* value()
  {
    return DataType< ::test::display_draw_pixel >::value();
  }
  static const char* value(const ::test::display_draw_pixelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::display_draw_pixelResponse> should match 
// service_traits::MD5Sum< ::test::display_draw_pixel > 
template<>
struct MD5Sum< ::test::display_draw_pixelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::display_draw_pixel >::value();
  }
  static const char* value(const ::test::display_draw_pixelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::display_draw_pixelResponse> should match 
// service_traits::DataType< ::test::display_draw_pixel > 
template<>
struct DataType< ::test::display_draw_pixelResponse>
{
  static const char* value()
  {
    return DataType< ::test::display_draw_pixel >::value();
  }
  static const char* value(const ::test::display_draw_pixelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_DISPLAY_DRAW_PIXEL_H
