// Generated by gencpp from file test/get_float.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_GET_FLOAT_H
#define TEST_MESSAGE_GET_FLOAT_H

#include <ros/service_traits.h>


#include <test/get_floatRequest.h>
#include <test/get_floatResponse.h>


namespace test
{

struct get_float
{

typedef get_floatRequest Request;
typedef get_floatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_float
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::get_float > {
  static const char* value()
  {
    return "896e758cc9f93e6fc99057486a02ac6a";
  }

  static const char* value(const ::test::get_float&) { return value(); }
};

template<>
struct DataType< ::test::get_float > {
  static const char* value()
  {
    return "test/get_float";
  }

  static const char* value(const ::test::get_float&) { return value(); }
};


// service_traits::MD5Sum< ::test::get_floatRequest> should match 
// service_traits::MD5Sum< ::test::get_float > 
template<>
struct MD5Sum< ::test::get_floatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::get_float >::value();
  }
  static const char* value(const ::test::get_floatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::get_floatRequest> should match 
// service_traits::DataType< ::test::get_float > 
template<>
struct DataType< ::test::get_floatRequest>
{
  static const char* value()
  {
    return DataType< ::test::get_float >::value();
  }
  static const char* value(const ::test::get_floatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::get_floatResponse> should match 
// service_traits::MD5Sum< ::test::get_float > 
template<>
struct MD5Sum< ::test::get_floatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::get_float >::value();
  }
  static const char* value(const ::test::get_floatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::get_floatResponse> should match 
// service_traits::DataType< ::test::get_float > 
template<>
struct DataType< ::test::get_floatResponse>
{
  static const char* value()
  {
    return DataType< ::test::get_float >::value();
  }
  static const char* value(const ::test::get_floatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_GET_FLOAT_H
