// Generated by gencpp from file test/motor_set_control_pidRequest.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_MOTOR_SET_CONTROL_PIDREQUEST_H
#define TEST_MESSAGE_MOTOR_SET_CONTROL_PIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct motor_set_control_pidRequest_
{
  typedef motor_set_control_pidRequest_<ContainerAllocator> Type;

  motor_set_control_pidRequest_()
    : controlp(0.0)
    , controli(0.0)
    , controld(0.0)  {
    }
  motor_set_control_pidRequest_(const ContainerAllocator& _alloc)
    : controlp(0.0)
    , controli(0.0)
    , controld(0.0)  {
  (void)_alloc;
    }



   typedef double _controlp_type;
  _controlp_type controlp;

   typedef double _controli_type;
  _controli_type controli;

   typedef double _controld_type;
  _controld_type controld;





  typedef boost::shared_ptr< ::test::motor_set_control_pidRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::motor_set_control_pidRequest_<ContainerAllocator> const> ConstPtr;

}; // struct motor_set_control_pidRequest_

typedef ::test::motor_set_control_pidRequest_<std::allocator<void> > motor_set_control_pidRequest;

typedef boost::shared_ptr< ::test::motor_set_control_pidRequest > motor_set_control_pidRequestPtr;
typedef boost::shared_ptr< ::test::motor_set_control_pidRequest const> motor_set_control_pidRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::motor_set_control_pidRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::motor_set_control_pidRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test': ['/home/nbhak/Desktop/test_ws/src/test/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test::motor_set_control_pidRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::motor_set_control_pidRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::motor_set_control_pidRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::motor_set_control_pidRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::motor_set_control_pidRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::motor_set_control_pidRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::motor_set_control_pidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ebf8f7154a3c8eec118cec294f2c32c";
  }

  static const char* value(const ::test::motor_set_control_pidRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ebf8f7154a3c8eeULL;
  static const uint64_t static_value2 = 0xc118cec294f2c32cULL;
};

template<class ContainerAllocator>
struct DataType< ::test::motor_set_control_pidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/motor_set_control_pidRequest";
  }

  static const char* value(const ::test::motor_set_control_pidRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::motor_set_control_pidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 controlp\n\
float64 controli\n\
float64 controld\n\
";
  }

  static const char* value(const ::test::motor_set_control_pidRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::motor_set_control_pidRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controlp);
      stream.next(m.controli);
      stream.next(m.controld);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_set_control_pidRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::motor_set_control_pidRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::motor_set_control_pidRequest_<ContainerAllocator>& v)
  {
    s << indent << "controlp: ";
    Printer<double>::stream(s, indent + "  ", v.controlp);
    s << indent << "controli: ";
    Printer<double>::stream(s, indent + "  ", v.controli);
    s << indent << "controld: ";
    Printer<double>::stream(s, indent + "  ", v.controld);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_MOTOR_SET_CONTROL_PIDREQUEST_H
