// Generated by gencpp from file test/node_get_static_balance.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_NODE_GET_STATIC_BALANCE_H
#define TEST_MESSAGE_NODE_GET_STATIC_BALANCE_H

#include <ros/service_traits.h>


#include <test/node_get_static_balanceRequest.h>
#include <test/node_get_static_balanceResponse.h>


namespace test
{

struct node_get_static_balance
{

typedef node_get_static_balanceRequest Request;
typedef node_get_static_balanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_static_balance
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::node_get_static_balance > {
  static const char* value()
  {
    return "1bb59681994e8cd9a01f91ec4bc81585";
  }

  static const char* value(const ::test::node_get_static_balance&) { return value(); }
};

template<>
struct DataType< ::test::node_get_static_balance > {
  static const char* value()
  {
    return "test/node_get_static_balance";
  }

  static const char* value(const ::test::node_get_static_balance&) { return value(); }
};


// service_traits::MD5Sum< ::test::node_get_static_balanceRequest> should match 
// service_traits::MD5Sum< ::test::node_get_static_balance > 
template<>
struct MD5Sum< ::test::node_get_static_balanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::node_get_static_balance >::value();
  }
  static const char* value(const ::test::node_get_static_balanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::node_get_static_balanceRequest> should match 
// service_traits::DataType< ::test::node_get_static_balance > 
template<>
struct DataType< ::test::node_get_static_balanceRequest>
{
  static const char* value()
  {
    return DataType< ::test::node_get_static_balance >::value();
  }
  static const char* value(const ::test::node_get_static_balanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::node_get_static_balanceResponse> should match 
// service_traits::MD5Sum< ::test::node_get_static_balance > 
template<>
struct MD5Sum< ::test::node_get_static_balanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::node_get_static_balance >::value();
  }
  static const char* value(const ::test::node_get_static_balanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::node_get_static_balanceResponse> should match 
// service_traits::DataType< ::test::node_get_static_balance > 
template<>
struct DataType< ::test::node_get_static_balanceResponse>
{
  static const char* value()
  {
    return DataType< ::test::node_get_static_balance >::value();
  }
  static const char* value(const ::test::node_get_static_balanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_NODE_GET_STATIC_BALANCE_H
