// Generated by gencpp from file test/supervisor_get_from_defRequest.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_SUPERVISOR_GET_FROM_DEFREQUEST_H
#define TEST_MESSAGE_SUPERVISOR_GET_FROM_DEFREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct supervisor_get_from_defRequest_
{
  typedef supervisor_get_from_defRequest_<ContainerAllocator> Type;

  supervisor_get_from_defRequest_()
    : name()
    , proto(0)  {
    }
  supervisor_get_from_defRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , proto(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint64_t _proto_type;
  _proto_type proto;





  typedef boost::shared_ptr< ::test::supervisor_get_from_defRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::supervisor_get_from_defRequest_<ContainerAllocator> const> ConstPtr;

}; // struct supervisor_get_from_defRequest_

typedef ::test::supervisor_get_from_defRequest_<std::allocator<void> > supervisor_get_from_defRequest;

typedef boost::shared_ptr< ::test::supervisor_get_from_defRequest > supervisor_get_from_defRequestPtr;
typedef boost::shared_ptr< ::test::supervisor_get_from_defRequest const> supervisor_get_from_defRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::supervisor_get_from_defRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::supervisor_get_from_defRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'test': ['/home/nbhak/Desktop/test_ws/src/test/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test::supervisor_get_from_defRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::supervisor_get_from_defRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::supervisor_get_from_defRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::supervisor_get_from_defRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::supervisor_get_from_defRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::supervisor_get_from_defRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::supervisor_get_from_defRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "178cf7495b55fb0d5a2e01c746ab4754";
  }

  static const char* value(const ::test::supervisor_get_from_defRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x178cf7495b55fb0dULL;
  static const uint64_t static_value2 = 0x5a2e01c746ab4754ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::supervisor_get_from_defRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/supervisor_get_from_defRequest";
  }

  static const char* value(const ::test::supervisor_get_from_defRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::supervisor_get_from_defRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
uint64 proto\n\
";
  }

  static const char* value(const ::test::supervisor_get_from_defRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::supervisor_get_from_defRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.proto);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct supervisor_get_from_defRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::supervisor_get_from_defRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::supervisor_get_from_defRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "proto: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.proto);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_SUPERVISOR_GET_FROM_DEFREQUEST_H
